// Each entry localizes the same purpose as its existing Italian/English page.
// Copy does not imply a launched product, guaranteed result or certification.
export const routes = [
 ['business','/intelligenza-artificiale-aziende','/en/ai-for-business','ia-entreprises','ia-empresas','ki-unternehmen'],
 ['professional','/ai-studi-professionali','/en/ai-for-professional-services','ia-professions-liberales','ia-profesionales','ki-freiberufler'],
 ['automation','/automazione-processi-aziendali','/en/business-process-automation','automatisation-processus','automatizacion-procesos','prozessautomatisierung'],
 ['about','/azienda','/en/about','a-propos','empresa','ueber-uns'],
 ['contact','/contatti','/en/contact','contact','contacto','kontakt'],
 ['accounting','/ai-per-commercialisti','/en/ai-for-accounting-firms','ia-cabinets-comptables','ia-asesorias-contables','ki-steuerkanzleien'],
 ['legal','/ai-per-studi-legali','/en/ai-for-law-firms','ia-cabinets-avocats','ia-despachos-abogados','ki-anwaltskanzleien'],
 ['payroll','/ai-consulenti-del-lavoro','/en/ai-for-payroll-hr-consultancies','ia-paie-rh','ia-nominas-rrhh','ki-lohn-personalberatung'],
 ['resources','/risorse','/en/resources','ressources','recursos','ratgeber'],
 ['confidential','/ai-studi-professionali-dati-riservati','/en/ai-professional-services-confidential-data','ia-donnees-confidentielles','ia-datos-confidenciales','ki-vertrauliche-daten'],
 ['priorities','/processi-aziendali-da-automatizzare','/en/which-business-processes-to-automate-first','quels-processus-automatiser','que-procesos-automatizar','welche-prozesse-automatisieren'],
];

export const languages = {
 fr: {
  home:'Accueil', projects:'Projets', resources:'Ressources', contact:'Contact', skip:'Aller au contenu', language:'Langue', applications:'Applications et points à vérifier', approach:'Définir un pilote utile', measure:'Comment évaluer le résultat', limits:'Limites et responsabilités', related:'Pour approfondir', sources:'Sources de référence',
  common:'Avant de connecter un outil, décrivez le processus actuel : informations reçues, systèmes utilisés, personnes responsables, étapes de validation et exceptions. Choisissez un cas limité et une mesure de départ. Testez avec des données synthétiques ou minimisées, puis faites examiner les résultats par la personne compétente. Définissez les conditions d’arrêt, le retour au processus manuel et la maintenance avant de généraliser.',
  scope:'Les exemples décrivent des usages à évaluer, pas des fonctionnalités promises ni une disponibilité immédiate. Le périmètre, les intégrations, les coûts et les délais sont confirmés pour chaque projet. Aucun gain de temps, taux de précision ou résultat commercial n’est garanti.',
  privacy:'La confidentialité dépend de la configuration réelle : accès par rôle, séparation des clients, conservation, suppression et fournisseurs impliqués. N’envoyez pas de documents confidentiels lors du premier contact. Une analyse du cadre juridique applicable reste nécessaire ; ces informations ne remplacent pas un avis professionnel.',
  cta:'Décrire votre besoin à Kreluna', date:'Mis à jour le 5 septembre 2026',
  pages:{
   business:['Intelligence artificielle pour les entreprises','Relier l’IA aux opérations de l’entreprise commence par un besoin observable, des sources autorisées et une personne responsable du résultat.', ['Rechercher dans des procédures approuvées et fournir les sources qui justifient la réponse.', 'Classer des demandes, préparer des synthèses et proposer un routage vers la bonne équipe.', 'Préparer des brouillons à partir d’informations autorisées, sans envoyer automatiquement de messages ni modifier les systèmes officiels.'], 'Comparer le temps par dossier, les corrections nécessaires, les réponses non étayées et les escalades au processus de départ. Compter aussi les coûts d’intégration et de contrôle.', 'Un pilote n’est pas un remplacement automatique du personnel ou du logiciel métier. Une connexion CRM ou ERP doit être étudiée, autorisée et testée.'],
   professional:['IA et automatisation pour les professions libérales','Documents, dossiers clients, messages et échéances peuvent bénéficier d’une préparation assistée, tout en préservant le jugement du professionnel.', ['Créer une chronologie à partir d’un dossier en citant chaque document utilisé.', 'Repérer les pièces manquantes et préparer une demande à faire valider.', 'Préparer des synthèses et des brouillons en séparant strictement les informations de chaque client.'], 'Mesurer le temps de préparation, les omissions, la fidélité aux sources et l’effort de révision, plutôt que le seul nombre de textes générés.', 'Avis, actes, déclarations, envois et décisions restent soumis à la validation du professionnel. Aucun outil ne garantit à lui seul le respect du secret professionnel.'],
   automation:['Automatisation des processus d’entreprise','Une automatisation utile relie les étapes du travail et traite les exceptions, au lieu de déplacer les erreurs plus rapidement.', ['Cartographier l’entrée des demandes, les règles de traitement et la sortie attendue.', 'Relier des systèmes à travers des interfaces autorisées et vérifier la qualité des données.', 'Prévoir doublons, informations manquantes, échecs techniques et reprise manuelle.'], 'Comparer délai total, taux d’erreur, reprises et coût de fonctionnement. Vérifier qu’un gain à une étape ne crée pas de travail supplémentaire ailleurs.', 'Un processus instable ou sans responsable doit d’abord être clarifié. Les actions irréversibles nécessitent des validations adaptées.'],
   accounting:['IA pour les cabinets comptables','L’IA peut préparer la collecte et la vérification documentaire, sans se substituer à l’expertise comptable ou aux outils officiels.', ['Classer les pièces reçues et signaler les justificatifs manquants.', 'Rapprocher des informations entre documents en indiquant les écarts à vérifier.', 'Préparer des listes de suivi, rappels et réponses à partir de sources approuvées.'], 'Suivre les pièces correctement classées, les omissions et le temps de vérification par dossier. Contrôler les montants, dates et références dans les originaux.', 'Calculs, déclarations, interprétations fiscales et transmissions doivent être vérifiés par le cabinet. Les règles applicables dépendent du pays et du cas.'],
   legal:['IA pour les cabinets d’avocats','La préparation de dossiers juridiques exige des sources vérifiables, la confidentialité et le contrôle de l’avocat.', ['Construire des chronologies avec renvoi aux pièces du dossier.', 'Comparer des versions contractuelles et lister les modifications à examiner.', 'Préparer un plan ou un brouillon en distinguant clairement faits établis, hypothèses et informations absentes.'], 'Évaluer la fidélité documentaire, les références introuvables, les omissions et le temps de révision. Toute citation juridique doit être vérifiée dans sa source.', 'L’IA peut inventer des références ou mal interpréter un texte. Elle ne fournit pas une décision juridique fiable sans examen professionnel et ne remplace pas l’avocat.'],
   payroll:['IA pour la paie et les ressources humaines','L’assistance numérique peut organiser les informations récurrentes destinées aux équipes de paie et de conseil RH.', ['Collecter les variations et signaler les informations incomplètes avant traitement.', 'Préparer des listes d’échéances et rapprocher les documents nécessaires.', 'Préparer des réponses à des questions récurrentes à partir de procédures validées.'], 'Mesurer les données manquantes détectées, les corrections, les délais et la charge de révision. Les résultats doivent être comparés au traitement habituel.', 'La paie, les décisions concernant les personnes et l’interprétation du droit du travail restent sous contrôle compétent. Limitez l’accès aux données des salariés.'],
   confidential:['Utiliser l’IA avec des données confidentielles','Avant de transmettre un dossier à un outil d’IA, déterminez quelles données sont nécessaires et quelles protections sont réellement disponibles.', ['Classer les données et retirer les éléments inutiles ; commencer par des exemples synthétiques.', 'Vérifier fournisseur, sous-traitants, usage pour l’entraînement, durée de conservation et suppression.', 'Définir les accès, la séparation des clients, les journaux utiles et la validation des sorties.'], 'Tester les permissions avec plusieurs rôles, vérifier les possibilités de suppression et chercher les fuites entre dossiers. Documenter les limites constatées avant le déploiement.', 'Une mention « entreprise » ou un hébergement européen ne suffit pas à garantir la conformité. Évaluez le rôle des parties, les transferts et la nécessité d’une analyse d’impact avec un spécialiste.'],
   priorities:['Quels processus automatiser en premier ?','Le meilleur premier projet est souvent un travail répétitif, stable et mesurable dont les erreurs sont réversibles.', ['Lister fréquence, volume, temps passé, systèmes et responsable de chaque processus.', 'Comparer stabilité des règles, qualité des données et proportion d’exceptions.', 'Choisir un pilote limité avec des critères de réussite et une procédure de retour manuel.'], 'Calculer le bénéfice net en incluant supervision, maintenance et corrections. Comparer une période représentative avant et après le pilote.', 'Ne commencez pas par une décision à fort impact, un processus mal défini ou une chaîne dont les données ne sont pas fiables. Automatiser un problème ne le résout pas.'],
   about:['À propos de Kreluna','Kreluna est un projet technologique italien consacré aux logiciels, à l’automatisation et aux expériences numériques.', ['Définir un besoin concret et un résultat vérifiable avant de choisir les outils.', 'Développer des projets avec une identité propre et un état d’avancement explicite.', 'Présenter CityBeam en pré-lancement et Velvet Table comme un concept en développement.'], 'Nous privilégions la clarté du périmètre, la traçabilité des informations et le contrôle humain. La disponibilité et les conditions sont confirmées projet par projet.', 'Kreluna ne présente pas de clientèle, de volumes, de partenariats finalisés ou de certifications qui n’ont pas été confirmés. P. IVA 02114130475 · REA PT-622714.'],
   contact:['Contacter Kreluna','Décrivez votre objectif, le travail concerné et les outils que vous utilisez. Un premier message suffit pour commencer à définir le périmètre.', ['Indiquez le résultat recherché, les utilisateurs concernés et le problème actuel.', 'Précisez les systèmes utilisés, les contraintes et le calendrier souhaité.', 'Pour CityBeam, indiquez destination, période, type de contenu et besoin de diffusion.'], 'Écrivez à andrea@kreluna.it. Nous pourrons préciser les informations nécessaires, les possibilités et les prochaines étapes adaptées à votre demande.', 'N’envoyez pas de mots de passe, dossiers clients ou données sensibles. Un message n’est ni une réservation publicitaire ni une confirmation de disponibilité.'],
   resources:['Ressources sur l’IA et l’automatisation','Des guides pour préparer un projet numérique, comparer les options et poser les bonnes questions avant de vous engager.', ['Protéger les données confidentielles lors de l’utilisation d’outils d’IA.', 'Choisir un premier processus à automatiser avec des critères mesurables.', 'Comparer les professionnels du web et les logiciels de gestion selon les besoins réels.'], 'Utilisez ces ressources pour préparer une liste de questions, vérifier les hypothèses et définir un test représentatif. Consultez les sources originales lorsque le sujet l’exige.', 'Ces contenus sont informatifs. Ils ne remplacent pas une analyse technique ou professionnelle de votre situation.'],
  }
 },
 es: {
  home:'Inicio', projects:'Proyectos', resources:'Recursos', contact:'Contacto', skip:'Ir al contenido', language:'Idioma', applications:'Aplicaciones y puntos que revisar', approach:'Definir una prueba útil', measure:'Cómo evaluar el resultado', limits:'Límites y responsabilidades', related:'Para profundizar', sources:'Fuentes de referencia',
  common:'Antes de conectar una herramienta, describa el proceso actual: información recibida, sistemas, responsables, aprobaciones y excepciones. Elija un caso limitado y una medición inicial. Pruebe con datos sintéticos o minimizados y solicite la revisión de la persona competente. Defina cuándo detener el proceso, cómo volver al trabajo manual y quién se ocupará del mantenimiento antes de ampliarlo.',
  scope:'Los ejemplos son usos que deben evaluarse, no funciones prometidas ni disponibilidad inmediata. El alcance, las integraciones, los costes y los plazos se confirman para cada proyecto. No se garantiza un ahorro de tiempo, una precisión concreta ni un resultado comercial.',
  privacy:'La confidencialidad depende de la configuración real: acceso por funciones, separación de clientes, conservación, eliminación y proveedores involucrados. No envíe documentos confidenciales en el primer contacto. Es necesario evaluar el marco jurídico aplicable; esta información no sustituye el asesoramiento profesional.',
  cta:'Describa su necesidad a Kreluna', date:'Actualizado el 5 de septiembre de 2026',
  pages:{
   business:['Inteligencia artificial para empresas','Conectar la IA con las operaciones empieza por una necesidad observable, fuentes autorizadas y una persona responsable del resultado.', ['Buscar en procedimientos aprobados e indicar las fuentes que justifican la respuesta.', 'Clasificar solicitudes, preparar resúmenes y proponer el equipo adecuado.', 'Preparar borradores con información autorizada sin enviar mensajes ni modificar automáticamente los sistemas oficiales.'], 'Compare el tiempo por caso, las correcciones, las respuestas sin respaldo y las derivaciones con el proceso inicial. Incluya el coste de integración y supervisión.', 'Una prueba no sustituye automáticamente al personal ni al software de gestión. Las conexiones con CRM o ERP deben estudiarse, autorizarse y probarse.'],
   professional:['IA y automatización para profesionales','La preparación de documentos, expedientes, mensajes y plazos puede beneficiarse de la IA sin perder el criterio profesional.', ['Crear cronologías citando cada documento utilizado.', 'Detectar documentación pendiente y preparar solicitudes para revisión.', 'Preparar resúmenes y borradores manteniendo separados los datos de cada cliente.'], 'Mida el tiempo de preparación, las omisiones, la fidelidad a las fuentes y el trabajo de revisión, no solo la cantidad de textos generados.', 'Informes, actuaciones, declaraciones, envíos y decisiones requieren la validación del profesional. Ninguna herramienta garantiza por sí sola el secreto profesional.'],
   automation:['Automatización de procesos empresariales','Una automatización útil conecta etapas y gestiona las excepciones, en lugar de trasladar los errores con mayor rapidez.', ['Describir la entrada de solicitudes, las reglas y el resultado esperado.', 'Conectar sistemas mediante interfaces autorizadas y verificar los datos.', 'Prever duplicados, información incompleta, fallos técnicos y recuperación manual.'], 'Compare plazos, errores, repeticiones y costes operativos. Compruebe que ahorrar trabajo en una etapa no crea más tareas en otra.', 'Un proceso inestable o sin responsable debe aclararse primero. Las acciones irreversibles requieren controles adecuados.'],
   accounting:['IA para asesorías contables','La IA puede preparar la recopilación y revisión documental sin sustituir el conocimiento contable ni las herramientas oficiales.', ['Clasificar documentos recibidos y señalar justificantes pendientes.', 'Comparar información entre documentos e indicar diferencias que revisar.', 'Preparar listas de seguimiento, recordatorios y respuestas desde fuentes aprobadas.'], 'Controle los documentos bien clasificados, las omisiones y el tiempo de revisión por expediente. Verifique importes, fechas y referencias en los originales.', 'Cálculos, declaraciones, interpretaciones fiscales y envíos deben ser revisados por la asesoría. Las normas dependen del país y del caso concreto.'],
   legal:['IA para despachos de abogados','Preparar expedientes jurídicos exige fuentes verificables, confidencialidad y control del abogado.', ['Construir cronologías con referencias a los documentos del expediente.', 'Comparar versiones de contratos y enumerar cambios para revisión.', 'Preparar esquemas y borradores distinguiendo hechos, hipótesis e información ausente.'], 'Evalúe la fidelidad documental, las referencias inexistentes, las omisiones y el tiempo de revisión. Verifique cada cita jurídica en su fuente original.', 'La IA puede inventar referencias o interpretar mal un texto. No ofrece una decisión jurídica fiable sin revisión profesional ni sustituye al abogado.'],
   payroll:['IA para nóminas y asesoría laboral','La asistencia digital puede organizar la información recurrente utilizada por equipos de nóminas y asesoría de recursos humanos.', ['Recopilar variaciones y detectar datos incompletos antes de procesarlos.', 'Preparar listas de plazos y relacionar los documentos necesarios.', 'Preparar respuestas a preguntas habituales a partir de procedimientos validados.'], 'Mida datos pendientes detectados, correcciones, plazos y carga de revisión. Compare con el tratamiento habitual.', 'Las nóminas, las decisiones sobre personas y la interpretación laboral permanecen bajo control competente. Limite el acceso a los datos de los empleados.'],
   confidential:['Utilizar IA con datos confidenciales','Antes de enviar un expediente a una herramienta de IA, determine qué datos necesita y qué protecciones están realmente disponibles.', ['Clasificar los datos y retirar lo innecesario; comenzar con ejemplos sintéticos.', 'Revisar proveedor, subcontratistas, uso para entrenamiento, conservación y eliminación.', 'Definir accesos, separación de clientes, registros útiles y validación de resultados.'], 'Pruebe permisos con distintos perfiles, verifique la eliminación y busque filtraciones entre expedientes. Documente los límites antes de implantar.', 'Una etiqueta empresarial o el alojamiento europeo no garantizan el cumplimiento. Evalúe funciones, transferencias y la necesidad de una evaluación de impacto con un especialista.'],
   priorities:['Qué procesos automatizar primero','Un buen primer proyecto suele ser una tarea repetitiva, estable y medible cuyos errores puedan corregirse.', ['Registrar frecuencia, volumen, tiempo, sistemas y responsable de cada proceso.', 'Comparar estabilidad de reglas, calidad de datos y proporción de excepciones.', 'Elegir una prueba limitada con criterios de éxito y retorno al trabajo manual.'], 'Calcule el beneficio neto incluyendo supervisión, mantenimiento y correcciones. Compare periodos representativos antes y después.', 'Evite empezar por decisiones de alto impacto, procesos poco definidos o cadenas con datos poco fiables. Automatizar un problema no lo resuelve.'],
   about:['Acerca de Kreluna','Kreluna es un proyecto tecnológico italiano dedicado al software, la automatización y las experiencias digitales.', ['Definir una necesidad concreta y un resultado verificable antes de elegir herramientas.', 'Desarrollar proyectos con identidad propia y un estado de avance explícito.', 'Presentar CityBeam en prelanzamiento y Velvet Table como concepto en desarrollo.'], 'Priorizamos un alcance claro, información verificable y control humano. La disponibilidad y las condiciones se confirman para cada proyecto.', 'No presentamos clientes, volúmenes, acuerdos cerrados ni certificaciones sin confirmar. P. IVA 02114130475 · REA PT-622714.'],
   contact:['Contactar con Kreluna','Describa su objetivo, el trabajo afectado y las herramientas que utiliza. Un primer mensaje permite empezar a definir el alcance.', ['Indique el resultado buscado, los usuarios y el problema actual.', 'Especifique sistemas, restricciones y calendario deseado.', 'Para CityBeam, indique destino, periodo, contenido y necesidad de difusión.'], 'Escriba a andrea@kreluna.it. Podremos concretar la información necesaria, las posibilidades y los siguientes pasos.', 'No envíe contraseñas, expedientes ni datos sensibles. Un mensaje no constituye una reserva publicitaria ni confirma disponibilidad.'],
   resources:['Recursos sobre IA y automatización','Guías para preparar un proyecto digital, comparar opciones y plantear las preguntas adecuadas antes de comprometerse.', ['Proteger datos confidenciales al utilizar herramientas de IA.', 'Elegir un primer proceso para automatizar con criterios medibles.', 'Comparar profesionales web y software de gestión según necesidades reales.'], 'Utilice estos recursos para preparar preguntas, comprobar supuestos y definir una prueba representativa. Consulte las fuentes originales cuando corresponda.', 'Son contenidos informativos y no sustituyen el análisis técnico o profesional de su situación.'],
  }
 },
 de: {
  home:'Startseite', projects:'Projekte', resources:'Ratgeber', contact:'Kontakt', skip:'Zum Inhalt', language:'Sprache', applications:'Anwendungen und Prüfpunkte', approach:'Einen sinnvollen Pilotversuch planen', measure:'Ergebnisse bewerten', limits:'Grenzen und Verantwortung', related:'Weiterführende Informationen', sources:'Referenzquellen',
  common:'Beschreiben Sie vor dem Anschluss eines Werkzeugs den aktuellen Ablauf: eingehende Informationen, Systeme, Verantwortliche, Freigaben und Ausnahmen. Wählen Sie einen begrenzten Fall und messen Sie den Ausgangszustand. Testen Sie mit synthetischen oder minimierten Daten und lassen Sie die Ergebnisse fachlich prüfen. Legen Sie Abbruchbedingungen, manuelle Ersatzverfahren und Wartung fest, bevor Sie den Einsatz ausweiten.',
  scope:'Die Beispiele beschreiben zu prüfende Einsatzmöglichkeiten, keine zugesagten Funktionen oder sofortige Verfügbarkeit. Umfang, Schnittstellen, Kosten und Termine werden je Projekt bestätigt. Zeitersparnis, Genauigkeit oder wirtschaftlicher Erfolg werden nicht garantiert.',
  privacy:'Vertraulichkeit hängt von der tatsächlichen Konfiguration ab: rollenbasierte Zugriffe, getrennte Kundendaten, Aufbewahrung, Löschung und beteiligte Anbieter. Senden Sie beim ersten Kontakt keine vertraulichen Unterlagen. Der rechtliche Rahmen muss für den Einzelfall geprüft werden; diese Informationen ersetzen keine fachliche Beratung.',
  cta:'Beschreiben Sie Kreluna Ihren Bedarf', date:'Aktualisiert am 5. September 2026',
  pages:{
   business:['Künstliche Intelligenz für Unternehmen','KI im Arbeitsalltag beginnt mit einem konkreten Bedarf, freigegebenen Quellen und einer Person, die das Ergebnis verantwortet.', ['In genehmigten Verfahren suchen und die Quellen einer Antwort nachvollziehbar angeben.', 'Anfragen einordnen, Zusammenfassungen vorbereiten und zuständige Teams vorschlagen.', 'Entwürfe aus autorisierten Informationen vorbereiten, ohne automatisch Nachrichten zu senden oder führende Systeme zu verändern.'], 'Vergleichen Sie Bearbeitungszeit, Korrekturen, unbelegte Antworten und Eskalationen mit dem Ausgangsprozess. Berücksichtigen Sie Integration und Prüfung.', 'Ein Pilot ersetzt weder Beschäftigte noch Fachsoftware automatisch. CRM- und ERP-Verbindungen müssen untersucht, freigegeben und getestet werden.'],
   professional:['KI und Automatisierung für freie Berufe','Dokumente, Mandantenakten, Nachrichten und Fristen lassen sich mit Unterstützung vorbereiten, während das fachliche Urteil beim Menschen bleibt.', ['Chronologien mit Verweisen auf die verwendeten Unterlagen erstellen.', 'Fehlende Dokumente erkennen und Rückfragen zur Freigabe vorbereiten.', 'Zusammenfassungen und Entwürfe bei strikter Trennung der Mandantendaten vorbereiten.'], 'Messen Sie Vorbereitungszeit, Auslassungen, Quellentreue und Prüfaufwand statt nur die Zahl erzeugter Texte.', 'Stellungnahmen, Erklärungen, Versand und Entscheidungen bleiben freigabepflichtig. Kein Werkzeug garantiert allein die Einhaltung beruflicher Verschwiegenheit.'],
   automation:['Geschäftsprozesse automatisieren','Sinnvolle Automatisierung verbindet Arbeitsschritte und behandelt Ausnahmen, statt Fehler lediglich schneller weiterzugeben.', ['Eingang, Regeln und erwartetes Ergebnis des Prozesses beschreiben.', 'Systeme über autorisierte Schnittstellen verbinden und die Datenqualität prüfen.', 'Dubletten, fehlende Angaben, technische Fehler und manuelle Wiederaufnahme vorsehen.'], 'Vergleichen Sie Durchlaufzeit, Fehler, Nacharbeit und Betriebskosten. Prüfen Sie, ob eine Entlastung an einer Stelle anderswo zusätzliche Arbeit verursacht.', 'Instabile Prozesse oder fehlende Zuständigkeiten müssen zuerst geklärt werden. Irreversible Aktionen benötigen angemessene Freigaben.'],
   accounting:['KI für Steuerkanzleien und Buchhaltung','KI kann Sammlung und Prüfung von Unterlagen vorbereiten, ohne fachliche Expertise oder offizielle Systeme zu ersetzen.', ['Eingegangene Belege zuordnen und fehlende Nachweise markieren.', 'Angaben zwischen Dokumenten vergleichen und Abweichungen zur Prüfung zeigen.', 'Übersichten, Erinnerungen und Antworten aus freigegebenen Quellen vorbereiten.'], 'Erfassen Sie korrekt zugeordnete Belege, Auslassungen und Prüfzeit pro Akte. Kontrollieren Sie Beträge, Daten und Verweise am Original.', 'Berechnungen, Erklärungen, steuerliche Auslegung und Übermittlung müssen fachlich geprüft werden. Maßgebliche Regeln hängen von Land und Einzelfall ab.'],
   legal:['KI für Anwaltskanzleien','Juristische Aktenvorbereitung verlangt überprüfbare Quellen, Vertraulichkeit und anwaltliche Kontrolle.', ['Chronologien mit Verweisen auf die Aktenstücke erstellen.', 'Vertragsfassungen vergleichen und Änderungen zur Prüfung auflisten.', 'Gliederungen und Entwürfe vorbereiten, dabei Tatsachen, Annahmen und fehlende Informationen unterscheiden.'], 'Bewerten Sie Dokumententreue, nicht auffindbare Fundstellen, Auslassungen und Prüfzeit. Jede juristische Quelle muss im Original verifiziert werden.', 'KI kann Fundstellen erfinden oder Texte falsch auslegen. Ohne fachliche Prüfung liefert sie keine verlässliche rechtliche Entscheidung und ersetzt keine anwaltliche Beratung.'],
   payroll:['KI für Lohnabrechnung und Personalberatung','Digitale Unterstützung kann wiederkehrende Informationen für Lohnabrechnung und Personalberatung organisieren.', ['Änderungen sammeln und unvollständige Angaben vor der Verarbeitung erkennen.', 'Fristenübersichten vorbereiten und erforderliche Unterlagen zuordnen.', 'Antworten auf wiederkehrende Fragen anhand freigegebener Verfahren vorbereiten.'], 'Messen Sie erkannte Datenlücken, Korrekturen, Fristen und Prüfaufwand im Vergleich zum bisherigen Ablauf.', 'Lohnabrechnung, Entscheidungen über Personen und arbeitsrechtliche Auslegung bleiben unter fachlicher Kontrolle. Beschränken Sie den Zugriff auf Beschäftigtendaten.'],
   confidential:['KI mit vertraulichen Daten nutzen','Klären Sie vor der Übermittlung einer Akte, welche Daten erforderlich sind und welche Schutzmaßnahmen das KI-Werkzeug tatsächlich bietet.', ['Daten klassifizieren und Unnötiges entfernen; mit synthetischen Beispielen beginnen.', 'Anbieter, Unterauftragnehmer, Trainingsnutzung, Aufbewahrung und Löschung prüfen.', 'Zugriffe, Mandantentrennung, sinnvolle Protokolle und Ergebnisfreigaben festlegen.'], 'Testen Sie Berechtigungen mit verschiedenen Rollen, überprüfen Sie Löschung und mögliche Datenübertritte zwischen Akten. Dokumentieren Sie Grenzen vor dem Einsatz.', 'Ein Unternehmensprodukt oder europäisches Hosting garantiert keine Konformität. Rollen, Übermittlungen und eine mögliche Folgenabschätzung müssen fachlich bewertet werden.'],
   priorities:['Welche Prozesse zuerst automatisieren?','Ein guter Einstieg ist meist eine wiederkehrende, stabile und messbare Aufgabe mit korrigierbaren Fehlern.', ['Häufigkeit, Umfang, Zeitaufwand, Systeme und Zuständigkeit je Prozess erfassen.', 'Stabilität der Regeln, Datenqualität und Anteil der Ausnahmen vergleichen.', 'Einen begrenzten Pilotversuch mit Erfolgskriterien und manuellem Rückweg auswählen.'], 'Berechnen Sie den Nettonutzen einschließlich Kontrolle, Wartung und Korrekturen. Vergleichen Sie repräsentative Zeiträume vor und nach dem Pilotversuch.', 'Beginnen Sie nicht mit folgenreichen Entscheidungen, unklaren Abläufen oder unzuverlässigen Datenketten. Automatisierung löst ein zugrunde liegendes Problem nicht von selbst.'],
   about:['Über Kreluna','Kreluna ist ein italienisches Technologieprojekt für Software, Automatisierung und digitale Erlebnisse.', ['Einen konkreten Bedarf und ein überprüfbares Ziel vor der Werkzeugwahl definieren.', 'Projekte mit eigener Identität und klar benanntem Entwicklungsstand aufbauen.', 'CityBeam vor dem Marktstart und Velvet Table als Konzept in Entwicklung vorstellen.'], 'Wir legen Wert auf einen klaren Umfang, nachvollziehbare Informationen und menschliche Kontrolle. Verfügbarkeit und Konditionen werden je Projekt bestätigt.', 'Wir behaupten keine unbestätigten Kunden, Volumina, abgeschlossenen Partnerschaften oder Zertifizierungen. P. IVA 02114130475 · REA PT-622714.'],
   contact:['Kreluna kontaktieren','Beschreiben Sie Ihr Ziel, den betroffenen Arbeitsablauf und Ihre Werkzeuge. Eine erste Nachricht hilft, den Umfang einzugrenzen.', ['Gewünschtes Ergebnis, betroffene Nutzer und aktuelles Problem nennen.', 'Systeme, Einschränkungen und gewünschten Zeitrahmen angeben.', 'Für CityBeam Zielort, Zeitraum, Inhalt und Ausstrahlungsbedarf nennen.'], 'Schreiben Sie an andrea@kreluna.it. Anschließend lassen sich erforderliche Informationen, Möglichkeiten und nächste Schritte konkretisieren.', 'Senden Sie keine Passwörter, Mandantenakten oder sensiblen Daten. Eine Nachricht ist keine Werbebuchung und bestätigt keine Verfügbarkeit.'],
   resources:['Ratgeber zu KI und Automatisierung','Informationen zur Vorbereitung digitaler Projekte, zum Vergleich von Optionen und für sinnvolle Fragen vor einer Beauftragung.', ['Vertrauliche Daten beim Einsatz von KI-Werkzeugen schützen.', 'Einen ersten Automatisierungsprozess anhand messbarer Kriterien auswählen.', 'Webprofis und Unternehmenssoftware anhand des tatsächlichen Bedarfs vergleichen.'], 'Nutzen Sie die Ratgeber für Ihre Fragenliste, zur Überprüfung von Annahmen und zur Planung eines repräsentativen Tests. Ziehen Sie bei Bedarf Originalquellen hinzu.', 'Die Inhalte dienen der Information und ersetzen keine technische oder fachliche Prüfung Ihres Einzelfalls.'],
  }
 }
};
