import type { Metadata } from "next";
import "../risonix.css";
import "../commerce.css";

export const metadata: Metadata = { title: "Termini di licenza Risonix | Kreluna", robots: { index: true, follow: true } };

export default function RisonixTermsPage() {
  return <main className="rx-account-page"><header className="rx-nav"><a className="rx-brand" href="/risonix"><span className="rx-mark">⌁</span><b>RISONIX</b></a></header><article className="rx-legal-card"><p className="rx-kicker"><i /> Condizioni di licenza</p><h1>Risonix 1.0</h1><p>La licenza è personale, non esclusiva, non trasferibile e si vincola al primo dispositivo sul quale viene attivata. Una reinstallazione sullo stesso dispositivo resta consentita; per guasti o sostituzioni è necessario contattare l’assistenza Kreluna.</p><h2>Uso consentito</h2><p>È consentito usare Risonix per analizzare file audio di cui il cliente dispone legittimamente. Non è consentito rivendere, distribuire, decompilare o aggirare i controlli di licenza, salvo quanto inderogabilmente previsto dalla legge.</p><h2>Connessione Internet</h2><p>Risonix richiede una connessione Internet all’avvio e prima delle funzioni protette. Senza una verifica online valida il riconoscimento e la riproduzione vengono sospesi.</p><h2>Aggiornamenti e compatibilità</h2><p>Kreluna può fornire aggiornamenti correttivi e di sicurezza. Formati, dispositivi e sistemi supportati sono quelli indicati nella pagina prodotto al momento dell’acquisto.</p><h2>Responsabilità</h2><p>Il software è uno strumento di riconoscimento: la percentuale esprime una stima tecnica e non garantisce l’identificazione in presenza di audio insufficiente, alterato o non presente nella raccolta collegata.</p><h2>Venditore</h2><p>Kreluna · P. IVA 02114130475 · REA PT-622714. Per assistenza usa i contatti pubblicati sul sito Kreluna.</p><small>Versione del 27 agosto 2026. Prima della vendita al pubblico, queste condizioni devono essere verificate da un professionista in base alla forma giuridica e al mercato di vendita.</small></article></main>;
}
