import type { Metadata } from 'next';
import PracticalGuide from './cosmora-guide-practical';
import { cosmoraCopy, cosmoraPath, type CosmoraLocale } from './cosmora-content';

const official = 'https://lucca2026.luccacomicsandgames.com/it/home';
export const guidePath = (l:CosmoraLocale) => `${l==='it'?'':`/${l}`}/cosmora/lucca-comics-2026`;
const locales:CosmoraLocale[] = ['it','en','fr','es','de'];
export const guideLanguages = Object.fromEntries([...locales.map(l=>[l,`https://www.kreluna.it${guidePath(l)}`]),['x-default',`https://www.kreluna.it${guidePath('it')}`]]);
export const guideLabels = {it:'Guida Lucca Comics 2026: cosplay, manga e stand',en:'Lucca Comics 2026 guide: cosplay, manga and stands',fr:'Guide Lucca Comics 2026 : cosplay, mangas et stands',es:'Guía Lucca Comics 2026: cosplay, manga y stands',de:'Lucca Comics 2026: Guide zu Cosplay, Manga und Ständen'};
const copy = {
 it: {
  title:'Lucca Comics 2026: cosplay, manga, fumetti e stand',
  intro:'Una guida indipendente per preparare la visita, cercare gli espositori e conoscere Cosmora, il progetto Kreluna dedicato alla community cosplay.',
  updated:'Verifica delle fonti: 6 settembre 2026', dates:'Quando si svolge?', dateText:'Il festival è in programma a Lucca dal 28 ottobre al 1 novembre 2026. Per modifiche, programma e condizioni di accesso fa fede l’organizzazione.', source:'Sito ufficiale dell’edizione 2026',
  stands:'Come trovare stand ed espositori', standText:'Parti dal sito ufficiale e cerca la voce “Mappa/Espositori”. Al momento della nostra verifica il collegamento rimanda alla home: non abbiamo quindi un elenco completo 2026 verificato da ripubblicare qui. Un annuncio di un ospite non conferma da solo il numero o la posizione di uno stand.',
  steps:['Cerca il nome dell’editore o del negozio, non solo quello del manga o del personaggio.', 'Controlla che la scheda si riferisca all’edizione 2026; annota padiglione, numero dello stand e fonte.', 'Prima della visita ricontrolla orari di firma, prenotazioni e posizione sul canale ufficiale dell’espositore.'],
  topics:[['Cosplay: prepara costume e incontri','Prima di partire consulta le regole ufficiali su accessori e oggetti di scena. Concorda un punto di ritrovo con la tua crew, prevedi pause e chiedi il consenso prima di fotografare altri partecipanti.'],['Manga e fumetti: costruisci la tua lista','Segna titoli, autori, editore e numeri mancanti della tua collezione. Per incontri e firmacopie verifica giorno, luogo e modalità di accesso: acquistare un volume non garantisce automaticamente una firma.'],['Collezionismo: confronta prima di acquistare','Per figure, carte e oggetti da collezione chiedi condizioni, edizione, prezzo e provenienza. Conserva la ricevuta e verifica le condizioni del venditore. Non tutti gli stand trattano le stesse categorie.']],
  useful:'Informazioni ufficiali utili', info:'Accessi, FAQ e assistenza', tickets:'Biglietti e condizioni',
  cosmora:'Dove entra in gioco Cosmora?', project:'Cosmora è il progetto Kreluna per condividere creazioni, esplorare cosplay e collezionismo e incontrare persone con interessi comuni. È ancora in sviluppo: questa guida è già consultabile, ma non è una mappa degli stand dentro l’app e non consente acquisti o prenotazioni. Non è l’app ufficiale di Lucca Comics & Games.',
 },
 en: {
  title:'Lucca Comics 2026: cosplay, manga, comics and stands', intro:'An independent guide to planning your visit, finding exhibitors and discovering Cosmora, Kreluna’s cosplay community project.', updated:'Sources checked: 6 September 2026', dates:'When is the festival?', dateText:'The festival is scheduled in Lucca from 28 October to 1 November 2026. The organiser is the authority for changes, schedules and admission rules.', source:'Official 2026 festival website',
  stands:'How to find stands and exhibitors', standText:'Start on the official website with “Mappa/Espositori”. At our check, that link leads back to the homepage, so we do not have a verified complete 2026 directory to republish here. A guest announcement alone does not confirm a stand number or location.',
  steps:['Search by publisher or shop name, not just the manga title or character.', 'Check that the listing is for 2026; record the pavilion, stand number and source.', 'Before visiting, reconfirm signing times, reservations and location with the exhibitor’s official channel.'],
  topics:[['Cosplay: plan your costume and meetups','Check official rules for accessories and props before travelling. Agree on a meeting point with your crew, plan breaks and ask permission before photographing other visitors.'],['Manga and comics: prepare a wish list','Note titles, creators, publishers and missing volumes in your collection. Check the date, location and admission process for signings: buying a book does not automatically guarantee a signature.'],['Collectibles: compare before buying','For figures, cards and collectibles, ask about condition, edition, price and provenance. Keep your receipt and check the seller’s terms. Different stands cover different categories.']],
  useful:'Useful official information', info:'Admission, FAQs and support', tickets:'Tickets and conditions', cosmora:'Where does Cosmora fit in?', project:'Cosmora is Kreluna’s project for sharing creations, exploring cosplay and collectibles and meeting people with shared interests. It is still in development: this guide is available now, but it is not an in-app stand map and does not provide purchases or bookings. It is not the official Lucca Comics & Games app.',
 },
 fr: {
  title:'Lucca Comics 2026 : cosplay, mangas, BD et stands', intro:'Un guide indépendant pour préparer votre visite, trouver les exposants et découvrir Cosmora, le projet de communauté cosplay de Kreluna.', updated:'Sources vérifiées le 6 septembre 2026', dates:'Quand a lieu le festival ?', dateText:'Le festival est prévu à Lucca du 28 octobre au 1er novembre 2026. Les changements, le programme et les conditions d’accès relèvent de l’organisateur.', source:'Site officiel du festival 2026',
  stands:'Comment trouver les stands et exposants', standText:'Sur le site officiel, cherchez « Mappa/Espositori ». Lors de notre vérification, ce lien renvoie à l’accueil : nous ne disposons donc pas d’un annuaire complet 2026 vérifié à publier ici. L’annonce d’un invité ne confirme pas à elle seule un numéro ou un emplacement de stand.',
  steps:['Cherchez le nom de l’éditeur ou de la boutique, pas seulement le manga ou le personnage.', 'Vérifiez l’édition 2026 ; notez le pavillon, le numéro du stand et la source.', 'Avant votre visite, confirmez les horaires des dédicaces, les réservations et le lieu sur le canal officiel de l’exposant.'],
  topics:[['Cosplay : costume et rencontres','Consultez les règles officielles sur les accessoires avant de partir. Fixez un point de rendez-vous avec votre groupe, prévoyez des pauses et demandez la permission avant de photographier les visiteurs.'],['Mangas et BD : préparez votre liste','Notez titres, auteurs, éditeurs et tomes manquants. Vérifiez la date, le lieu et les modalités des dédicaces : acheter un livre ne garantit pas automatiquement une signature.'],['Collections : comparez avant d’acheter','Pour les figurines, cartes et objets de collection, demandez l’état, l’édition, le prix et la provenance. Gardez le reçu et vérifiez les conditions du vendeur. Les catégories varient selon les stands.']],
  useful:'Informations officielles utiles', info:'Accès, FAQ et assistance', tickets:'Billets et conditions', cosmora:'Et Cosmora ?', project:'Cosmora est le projet Kreluna pour partager des créations, explorer le cosplay et les collections et rencontrer d’autres passionnés. Il est en développement : ce guide est consultable, mais ce n’est pas une carte des stands dans l’application et il ne permet ni achats ni réservations. Ce n’est pas l’application officielle de Lucca Comics & Games.',
 },
 es: {
  title:'Lucca Comics 2026: cosplay, manga, cómics y stands', intro:'Una guía independiente para preparar tu visita, buscar expositores y descubrir Cosmora, el proyecto de comunidad cosplay de Kreluna.', updated:'Fuentes verificadas: 6 de septiembre de 2026', dates:'¿Cuándo es el festival?', dateText:'El festival está previsto en Lucca del 28 de octubre al 1 de noviembre de 2026. La organización confirma los cambios, el programa y las condiciones de acceso.', source:'Web oficial de la edición 2026',
  stands:'Cómo encontrar stands y expositores', standText:'En la web oficial busca “Mappa/Espositori”. Al comprobarlo, ese enlace lleva a la página de inicio: no tenemos un directorio completo de 2026 verificado para publicarlo aquí. Anunciar un invitado no confirma por sí solo el número ni la ubicación de un stand.',
  steps:['Busca por editorial o tienda, no solo por manga o personaje.', 'Comprueba que sea la edición 2026; anota el pabellón, número del stand y fuente.', 'Antes de ir, confirma horarios de firmas, reservas y ubicación en el canal oficial del expositor.'],
  topics:[['Cosplay: prepara el disfraz y los encuentros','Consulta las normas oficiales sobre accesorios antes de viajar. Acuerda un punto de encuentro con tu grupo, planifica descansos y pide permiso antes de fotografiar a otros visitantes.'],['Manga y cómics: prepara tu lista','Anota títulos, autores, editoriales y tomos que te faltan. Confirma fecha, lugar y acceso a las firmas: comprar un libro no garantiza automáticamente una dedicatoria.'],['Coleccionismo: compara antes de comprar','Para figuras, cartas y coleccionables pregunta por estado, edición, precio y procedencia. Conserva el recibo y revisa las condiciones del vendedor. Cada stand puede ofrecer categorías distintas.']],
  useful:'Información oficial útil', info:'Acceso, preguntas frecuentes y ayuda', tickets:'Entradas y condiciones', cosmora:'¿Dónde encaja Cosmora?', project:'Cosmora es el proyecto de Kreluna para compartir creaciones, explorar cosplay y coleccionismo y conocer personas con intereses comunes. Sigue en desarrollo: esta guía ya se puede consultar, pero no es un mapa de stands dentro de la app ni permite compras o reservas. No es la aplicación oficial de Lucca Comics & Games.',
 },
 de: {
  title:'Lucca Comics 2026: Cosplay, Manga, Comics und Stände', intro:'Ein unabhängiger Guide zur Besuchsplanung, Ausstellersuche und zu Cosmora, Krelunas Projekt für die Cosplay-Community.', updated:'Quellen geprüft: 6. September 2026', dates:'Wann findet das Festival statt?', dateText:'Das Festival ist in Lucca vom 28. Oktober bis 1. November 2026 geplant. Für Änderungen, Programm und Einlassbedingungen ist der Veranstalter maßgeblich.', source:'Offizielle Festival-Website 2026',
  stands:'Stände und Aussteller finden', standText:'Suche auf der offiziellen Website nach „Mappa/Espositori“. Bei unserer Prüfung führte der Link zur Startseite. Deshalb veröffentlichen wir hier kein unbestätigtes vollständiges Ausstellerverzeichnis 2026. Eine Gastankündigung bestätigt allein weder Standnummer noch Standort.',
  steps:['Suche nach Verlag oder Geschäft, nicht nur nach Manga-Titel oder Figur.', 'Prüfe die Ausgabe 2026 und notiere Halle, Standnummer und Quelle.', 'Bestätige vor dem Besuch Signierzeiten, Reservierungen und Standort über den offiziellen Kanal des Ausstellers.'],
  topics:[['Cosplay: Kostüm und Treffen planen','Prüfe vor der Anreise die offiziellen Regeln zu Zubehör und Requisiten. Vereinbare einen Treffpunkt mit deiner Gruppe, plane Pausen und frage vor Fotos anderer Besucher um Erlaubnis.'],['Manga und Comics: Wunschliste vorbereiten','Notiere Titel, Autoren, Verlage und fehlende Bände. Prüfe Datum, Ort und Zugang zu Signierstunden: Ein Buchkauf garantiert nicht automatisch eine Signatur.'],['Sammlerstücke: vor dem Kauf vergleichen','Frage bei Figuren, Karten und Sammlerstücken nach Zustand, Ausgabe, Preis und Herkunft. Bewahre den Beleg auf und prüfe die Bedingungen des Verkäufers. Nicht jeder Stand führt dieselben Kategorien.']],
  useful:'Nützliche offizielle Informationen', info:'Einlass, FAQ und Hilfe', tickets:'Tickets und Bedingungen', cosmora:'Welche Rolle spielt Cosmora?', project:'Cosmora ist Krelunas Projekt zum Teilen von Kreationen, Entdecken von Cosplay und Sammlerstücken und Kennenlernen Gleichgesinnter. Es ist noch in Entwicklung. Dieser Guide ist bereits lesbar, aber keine Standkarte in der App und bietet weder Käufe noch Buchungen. Cosmora ist nicht die offizielle App von Lucca Comics & Games.',
 },
};
export function guideMetadata(l:CosmoraLocale):Metadata {
 const t=copy[l],url=`https://www.kreluna.it${guidePath(l)}`;
 return {title:`${t.title} | Cosmora`,description:t.intro,alternates:{canonical:url,languages:guideLanguages},openGraph:{title:t.title,description:t.intro,url,type:'article',images:[]},twitter:{card:'summary',title:t.title,description:t.intro,images:[]}};
}
export default function CosmoraGuide({locale}:{locale:CosmoraLocale}) {
 const t=copy[locale],p=cosmoraCopy[locale],url=`https://www.kreluna.it${guidePath(locale)}`;
 const crumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:p.home,item:`https://www.kreluna.it${locale==='it'?'/':`/${locale}`}`},{'@type':'ListItem',position:2,name:'Cosmora',item:`https://www.kreluna.it${cosmoraPath(locale)}`},{'@type':'ListItem',position:3,name:t.title,item:url}]};
 const data={'@context':'https://schema.org','@type':'Article',headline:t.title,description:t.intro,inLanguage:locale,datePublished:'2026-09-06',dateModified:'2026-09-06',mainEntityOfPage:url,author:{'@type':'Organization',name:'Kreluna',url:'https://www.kreluna.it/'},publisher:{'@type':'Organization',name:'Kreluna',url:'https://www.kreluna.it/'}};
 return <div lang={locale}><a className="skip-link" href="#guide-main">{p.skip}</a><header className="cosmora-header"><a href={locale==='it'?'/':`/${locale}`}>KRELUNA <span>· COSMORA</span></a><a href={cosmoraPath(locale)}>Cosmora</a><nav aria-label={p.languages}>{locales.map(l=><a key={l} href={guidePath(l)} hrefLang={l} lang={l} aria-label={{it:'Italiano',en:'English',fr:'Français',es:'Español',de:'Deutsch'}[l]} aria-current={l===locale?'page':undefined}>{l.toUpperCase()}</a>)}</nav></header>
 <main id="guide-main" tabIndex={-1} className="cosmora-guide section-shell"><article><p><a href={locale==='it'?'/':`/${locale}`}>{p.home}</a> / <a href={cosmoraPath(locale)}>Cosmora</a> / Lucca Comics 2026</p><p className="cosmora-kicker">COSMORA · GUIDE</p><h1>{t.title}</h1><p className="guide-lead">{t.intro}</p><p className="cosmora-notice">{t.updated}</p><nav className="guide-index" aria-label={t.title}><a href="#stands">{t.stands}</a><a href="#cosplay">Cosplay</a><a href="#manga">Manga</a><a href="#practical">{ {it:'Domande pratiche',en:'Practical questions',fr:'Questions pratiques',es:'Preguntas prácticas',de:'Praktische Fragen'}[locale]}</a><a href="#cosmora">Cosmora</a></nav>
 <section><h2>{t.dates}</h2><p>{t.dateText}</p><a href={official}>{t.source} ↗</a></section>
 <section id="stands"><h2>{t.stands}</h2><p>{t.standText}</p><ol>{t.steps.map(s=><li key={s}>{s}</li>)}</ol><a href={official}>{t.source} ↗</a></section>
 {t.topics.map(([title,body],i)=><section key={title} id={['cosplay','manga','collect'][i]}><h2>{title}</h2><p>{body}</p></section>)}
 <PracticalGuide locale={locale} />
 <section><h2>{t.useful}</h2><ul><li><a href="https://lucca2026.luccacomicsandgames.com/it/info">{t.info} ↗</a></li><li><a href="https://lucca2026.luccacomicsandgames.com/it/biglietti">{t.tickets} ↗</a></li></ul></section>
 <section id="cosmora" className="cosmora-event"><h2>{t.cosmora}</h2><p>{t.project}</p><p className="cosmora-notice">{p.independent}</p><a className="button button-primary" href={cosmoraPath(locale)}>{p.discover} ↗</a></section>
 </article></main><footer className="projects-page-footer">© 2026 Kreluna · P. IVA 02114130475 · REA PT-622714</footer><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([data,crumbs])}} /></div>;
}
