/* eslint-disable @next/next/no-img-element */
import type { Metadata } from 'next';
export type CosmoraLocale = 'it' | 'en' | 'fr' | 'es' | 'de';
export const cosmoraCopy = {
  it: { status:'In sviluppo', label:'Il prossimo mondo Kreluna', title:'Il tuo mondo cosplay, tutto da incontrare.', intro:'Creazioni, collezionismo e persone che condividono le tue passioni. Cosmora riunisce la community, dentro e fuori dagli eventi.', discover:'Scopri Cosmora', home:'Home', projects:'Tutti i progetti', contact:'Chiedi informazioni', skip:'Vai al contenuto', languages:'Scegli la lingua', preview:'Immagine del progetto Cosmora', heading:'Le passioni diventano connessioni.', features:[['Community','Uno spazio per condividere creazioni, foto e video e conoscere altri appassionati.'],['Cosplay e collezionismo','Annunci e profili per esplorare cosplay, manga, fumetti, figure, carte e gaming.'],['Crew e incontri','Gruppi, messaggi ed eventi per trovare persone con cui condividere la stessa passione.']], eventTitle:'Ti stai preparando per Lucca Comics & Games?', event:'Cosmora nasce per il mondo del cosplay e del collezionismo: anche per chi frequenta eventi come Lucca Comics & Games e vuole conoscere altre persone e condividere le proprie creazioni. Stiamo lavorando alla versione pubblica: questa pagina presenta il progetto, non un servizio ufficiale dell’evento.', notice:'Versione di test. Il lancio pubblico non ha ancora una data confermata. Pagamenti e acquisti reali non sono disponibili.', independent:'Cosmora è un progetto indipendente di Kreluna, non affiliato a Lucca Comics & Games o agli altri organizzatori e marchi citati.' },
  en: { status:'In development', label:'The next Kreluna world', title:'Your cosplay world. Your people.', intro:'Creations, collectibles and people who share your passions. Cosmora brings the community together, at events and beyond.', discover:'Explore Cosmora', home:'Home', projects:'All projects', contact:'Ask for information', skip:'Skip to content', languages:'Choose language', preview:'Cosmora project artwork', heading:'Shared passions. New connections.', features:[['Community','A space to share creations, photos and videos and meet fellow fans.'],['Cosplay & collectibles','Listings and profiles to explore cosplay, manga, comics, figures, cards and gaming.'],['Crews & meetups','Groups, messages and events to find people who share your passion.']], eventTitle:'Getting ready for Lucca Comics & Games?', event:'Cosmora is being built for cosplay and collecting communities, including people attending events such as Lucca Comics & Games who want to connect and share their creations. We are working towards a public release: this page introduces the project, not an official event service.', notice:'Test version. A public launch date has not been confirmed. Real payments and purchases are not available.', independent:'Cosmora is an independent Kreluna project, not affiliated with Lucca Comics & Games or other organisers and brands mentioned.' },
  fr: { status:'En développement', label:'Le prochain univers Kreluna', title:'Votre univers cosplay. Vos rencontres.', intro:'Des créations, des collections et des personnes qui partagent vos passions. Cosmora réunit la communauté, pendant les événements et au-delà.', discover:'Découvrir Cosmora', home:'Accueil', projects:'Tous les projets', contact:'Demander des informations', skip:'Aller au contenu', languages:'Choisir la langue', preview:'Illustration du projet Cosmora', heading:'Des passions communes. De nouvelles rencontres.', features:[['Communauté','Un espace pour partager créations, photos et vidéos et rencontrer d’autres passionnés.'],['Cosplay et collections','Des annonces et des profils pour explorer cosplay, mangas, BD, figurines, cartes et jeux vidéo.'],['Groupes et rencontres','Des groupes, messages et événements pour rencontrer des personnes qui partagent votre passion.']], eventTitle:'Vous préparez votre visite à Lucca Comics & Games ?', event:'Cosmora est conçu pour les communautés du cosplay et de la collection, notamment pour les visiteurs d’événements comme Lucca Comics & Games souhaitant échanger et partager leurs créations. La version publique est en préparation : cette page présente le projet, pas un service officiel de l’événement.', notice:'Version de test. Aucune date de lancement public n’est confirmée. Les paiements et achats réels ne sont pas disponibles.', independent:'Cosmora est un projet indépendant de Kreluna, sans affiliation à Lucca Comics & Games ni aux autres organisateurs et marques cités.' },
  es: { status:'En desarrollo', label:'El próximo mundo Kreluna', title:'Tu mundo cosplay. Tu comunidad.', intro:'Creaciones, coleccionismo y personas que comparten tus pasiones. Cosmora reúne a la comunidad, dentro y fuera de los eventos.', discover:'Descubrir Cosmora', home:'Inicio', projects:'Todos los proyectos', contact:'Pedir información', skip:'Ir al contenido', languages:'Elegir idioma', preview:'Ilustración del proyecto Cosmora', heading:'Pasiones compartidas. Nuevas conexiones.', features:[['Comunidad','Un espacio para compartir creaciones, fotos y vídeos y conocer a otros aficionados.'],['Cosplay y coleccionismo','Anuncios y perfiles para explorar cosplay, manga, cómics, figuras, cartas y videojuegos.'],['Grupos y encuentros','Grupos, mensajes y eventos para encontrar personas con tu misma pasión.']], eventTitle:'¿Te preparas para Lucca Comics & Games?', event:'Cosmora se está creando para las comunidades del cosplay y el coleccionismo, también para quienes visitan eventos como Lucca Comics & Games y quieren conocer gente y compartir sus creaciones. La versión pública está en preparación: esta página presenta el proyecto, no un servicio oficial del evento.', notice:'Versión de prueba. No hay una fecha de lanzamiento público confirmada. Los pagos y compras reales no están disponibles.', independent:'Cosmora es un proyecto independiente de Kreluna, sin afiliación a Lucca Comics & Games ni a los demás organizadores y marcas mencionados.' },
  de: { status:'In Entwicklung', label:'Die nächste Kreluna Welt', title:'Deine Cosplay-Welt. Deine Community.', intro:'Kreationen, Sammlerstücke und Menschen, die deine Leidenschaft teilen. Cosmora verbindet die Community – auf Events und darüber hinaus.', discover:'Cosmora entdecken', home:'Startseite', projects:'Alle Projekte', contact:'Informationen anfragen', skip:'Zum Inhalt', languages:'Sprache wählen', preview:'Illustration zum Projekt Cosmora', heading:'Gemeinsame Interessen. Neue Kontakte.', features:[['Community','Ein Ort, um Kreationen, Fotos und Videos zu teilen und andere Fans kennenzulernen.'],['Cosplay und Sammeln','Anzeigen und Profile rund um Cosplay, Manga, Comics, Figuren, Karten und Gaming.'],['Crews und Treffen','Gruppen, Nachrichten und Veranstaltungen für Menschen mit gemeinsamen Interessen.']], eventTitle:'Bereitest du dich auf Lucca Comics & Games vor?', event:'Cosmora entsteht für die Cosplay- und Sammlercommunity – auch für Besucher von Veranstaltungen wie Lucca Comics & Games, die Kontakte knüpfen und ihre Kreationen teilen möchten. Die öffentliche Version ist in Vorbereitung. Diese Seite stellt das Projekt vor, keinen offiziellen Veranstaltungsdienst.', notice:'Testversion. Ein öffentlicher Starttermin steht noch nicht fest. Echte Zahlungen und Käufe sind nicht verfügbar.', independent:'Cosmora ist ein unabhängiges Kreluna Projekt und nicht mit Lucca Comics & Games oder anderen genannten Veranstaltern und Marken verbunden.' }
};
export const cosmoraPath = (locale:CosmoraLocale) => locale === 'it' ? '/cosmora' : `/${locale}/cosmora`;
export const cosmoraLanguages = Object.fromEntries([...(['it','en','fr','es','de'] as CosmoraLocale[]).map(l=>[l,`https://www.kreluna.it${cosmoraPath(l)}`]),['x-default','https://www.kreluna.it/cosmora']]);
export function cosmoraMetadata(locale:CosmoraLocale):Metadata {
  const t=cosmoraCopy[locale], title=`Cosmora | ${t.title}`;
  return {title,description:t.intro,alternates:{canonical:`https://www.kreluna.it${cosmoraPath(locale)}`,languages:cosmoraLanguages},openGraph:{title,description:t.intro,url:`https://www.kreluna.it${cosmoraPath(locale)}`,type:'website',images:[]},twitter:{card:'summary',title,description:t.intro,images:[]}};
}
export function CosmoraFeature({locale}:{locale:CosmoraLocale}) {
  const t=cosmoraCopy[locale];
  return <article className="cosmora-feature">
    <picture><source media="(max-width:640px)" srcSet="/cosmora-hero-mobile.jpg" /><img src="/cosmora-hero.jpg" alt="" width="1672" height="941" loading="lazy" decoding="async" /></picture>
    <div className="cosmora-feature-copy"><span className="cosmora-status">{t.status}</span><p className="cosmora-kicker">{t.label}</p><h3>COSMORA</h3><p className="cosmora-tagline">{t.title}</p><p>{t.intro}</p><a className="button button-primary" href={cosmoraPath(locale)}>{t.discover} <span aria-hidden="true">↗</span></a></div>
  </article>;
}
export default function CosmoraPage({locale}:{locale:CosmoraLocale}) {
  const t=cosmoraCopy[locale], root=locale==='it'?'/':`/${locale}`, contact={it:'/contatti',en:'/en/contact',fr:'/fr/contact',es:'/es/contacto',de:'/de/kontakt'}[locale];
  const data={'@context':'https://schema.org','@type':'WebPage',name:`Cosmora | ${t.title}`,description:t.intro,url:`https://www.kreluna.it${cosmoraPath(locale)}`,inLanguage:locale,about:{'@type':'CreativeWork',name:'Cosmora',creativeWorkStatus:t.status,creator:{'@type':'Organization',name:'Kreluna',url:'https://www.kreluna.it/'}}};
  return <div className="cosmora-page" lang={locale}>
    <a className="skip-link" href="#cosmora-main">{t.skip}</a>
    <header className="cosmora-header"><a href={root}>KRELUNA <span>· COSMORA</span></a><a href={root}>{t.home}</a><nav aria-label={t.languages}>{(['it','en','fr','es','de'] as CosmoraLocale[]).map(l=><a href={cosmoraPath(l)} key={l} hrefLang={l} lang={l} aria-label={{it:'Italiano',en:'English',fr:'Français',es:'Español',de:'Deutsch'}[l]} aria-current={locale===l?'page':undefined}>{l.toUpperCase()}</a>)}</nav></header>
    <main id="cosmora-main" tabIndex={-1}>
      <section className="cosmora-intro section-shell"><span className="cosmora-status">{t.status}</span><p className="cosmora-kicker">COSMORA · COSPLAY & COLLECT</p><h1>{t.title}</h1><p>{t.intro}</p><a className="button button-primary" href={contact}>{t.contact} ↗</a><p className="cosmora-notice">{t.notice}</p></section>
      <figure className="cosmora-art section-shell"><picture><source media="(max-width:640px)" srcSet="/cosmora-hero-mobile.jpg" /><img src="/cosmora-hero.jpg" alt={t.preview} width="1672" height="941" decoding="async" /></picture><figcaption>{t.preview}</figcaption></figure>
      <section className="cosmora-details section-shell"><h2>{t.heading}</h2><div className="cosmora-functions">{t.features.map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><aside className="cosmora-event"><h2>{t.eventTitle}</h2><p>{t.event}</p><p className="cosmora-notice">{t.independent}</p></aside><a href={locale==='it'?'/progetti':`/${locale}/projects`}>{t.projects} ↗</a></section>
    </main><footer className="projects-page-footer">© 2026 Kreluna · P. IVA 02114130475 · REA PT-622714</footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}} />
  </div>;
}
