import { PACKAGES, serializeLuna } from "./luna";
import type {
  Activity,
  Approval,
  CalEvent,
  CaseItem,
  Finding,
  FsNode,
  MailItem,
  Note,
  Notif,
  Reminder,
} from "./types";

export const CASES: CaseItem[] = [
  {
    id: "c1",
    code: "ACM-0412",
    title: "Revisione contratto di fornitura",
    client: "Acme Industria",
    status: "review",
    deadline: "18 ago",
    owner: "M. Ricci",
  },
  {
    id: "c2",
    code: "BRN-0190",
    title: "Flusso fatture e scadenze",
    client: "Bruni & Associati",
    status: "open",
    deadline: "22 ago",
    owner: "L. Costa",
  },
  {
    id: "c3",
    code: "VEL-0077",
    title: "Policy accesso documenti",
    client: "Velia Studio",
    status: "open",
    deadline: "25 ago",
    owner: "S. Greco",
  },
  {
    id: "c4",
    code: "NRT-1102",
    title: "Chiusura pratica Q2",
    client: "Nortech",
    status: "done",
    deadline: "01 ago",
    owner: "M. Ricci",
  },
];

export const FINDINGS: Finding[] = [
  {
    id: "f1",
    cve: "CVE-2024-38475",
    title: "Configurazione TLS obsoleta su edge",
    severity: "high",
    asset: "edge-01.interno",
    status: "open",
  },
  {
    id: "f2",
    cve: "KRE-INT-18",
    title: "Account di servizio con privilegi ampi",
    severity: "medium",
    asset: "idp.interno",
    status: "open",
  },
  {
    id: "f3",
    cve: "CVE-2025-24813",
    title: "Patch disponibile, non applicata",
    severity: "medium",
    asset: "app-docs",
    status: "accepted",
  },
  {
    id: "f4",
    cve: "KRE-INT-03",
    title: "Backup non verificato da 21 giorni",
    severity: "low",
    asset: "vault-b",
    status: "open",
  },
];

export const MAILS: MailItem[] = [
  {
    id: "m1",
    from: "Marta Ricci",
    fromEmail: "m.ricci@studio.local",
    subject: "Approvazione richiesta — ACM-0412",
    preview: "Il contratto è pronto. Serve la tua revisione prima di inviarlo.",
    body: "Buonasera.\n\nIl contratto di fornitura ACM-0412 è nella coda di revisione. Ho evidenziato le clausole su responsabilità e trattamento dati.\n\nKreluna Office non lo invierà senza la tua approvazione.\n\nMarta",
    time: "09:14",
    unread: true,
    tag: "Office",
  },
  {
    id: "m2",
    from: "Kreluna Cyber",
    fromEmail: "cyber@kreluna.os",
    subject: "Assessment Q3 — bozza, non certificazione",
    preview: "Quattro rilievi aperti. Nessuno è stato pubblicato all’esterno.",
    body: "Assessment interno concluso.\n\nAperti: 4. Critici: 0. Alti: 1.\nQuesto messaggio non è una certificazione e non va inoltrato come tale.\n\nApri Cyber per la coda di revisione.",
    time: "08:02",
    unread: true,
    tag: "Cyber",
  },
  {
    id: "m3",
    from: "Luca Costa",
    fromEmail: "l.costa@bruni.local",
    subject: "Flusso fatture — confini",
    preview: "Confermo: Core può preparare, non può inviare.",
    body: "Perfetto. Allora i confini sono:\n\n— Core prepara la bozza\n— Office organizza scadenze\n— Invio solo dopo approvazione umana\n\nLuca",
    time: "Ieri",
    unread: false,
    tag: "Office",
  },
];

export const NOTES: Note[] = [
  {
    id: "n1",
    title: "Principi Kreluna",
    body: "Controllo umano. Niente decisioni autonome su azioni rilevanti. Niente certificazioni inventate.",
    updated: "Oggi",
  },
  {
    id: "n2",
    title: "Cosa non promettere",
    body: "Niente clienti inventati. Niente percentuali. Niente certificazioni. Niente autonomia su decisioni rilevanti.",
    updated: "Ieri",
  },
];

export const EVENTS: CalEvent[] = [
  { id: "e1", title: "Revisione ACM-0412", day: 5, start: "10:00", end: "10:45", place: "Office", kind: "review" },
  { id: "e2", title: "Focus — policy AI", day: 5, start: "14:00", end: "16:00", place: "Core", kind: "focus" },
  { id: "e3", title: "Allineamento Cyber", day: 6, start: "09:30", end: "10:15", place: "Cyber", kind: "meet" },
  { id: "e4", title: "Bruni — confini flusso", day: 1, start: "11:00", end: "11:30", place: "Meet", kind: "meet" },
  { id: "e5", title: "Chiusura settimanale", day: 4, start: "17:00", end: "17:30", place: "Office", kind: "review" },
];

export const SEED_NOTIFS: Notif[] = [
  {
    id: "n1",
    appId: "office",
    title: "Approvazione richiesta",
    body: "Contratto ACM-0412 in attesa della tua revisione.",
    time: "09:14",
    read: false,
    kind: "review",
  },
  {
    id: "n2",
    appId: "cyber",
    title: "Assessment concluso",
    body: "Quattro rilievi. Nessuna certificazione emessa.",
    time: "08:02",
    read: false,
    kind: "info",
  },
];

export const SEED_APPROVALS: Approval[] = [
  {
    id: "a1",
    title: "Inviare bozza contratto ACM-0412",
    detail: "Office ha preparato il documento. L’invio resta fermo finché non approvi.",
    source: "office",
    risk: "medium",
    status: "pending",
  },
  {
    id: "a2",
    title: "Esportare rapporto Cyber Q3",
    detail: "Il rapporto è una bozza interna. Esportarlo non equivale a certificare.",
    source: "cyber",
    risk: "low",
    status: "pending",
  },
];

export const TREND = [
  { w: "S1", open: 9, closed: 2 },
  { w: "S2", open: 8, closed: 3 },
  { w: "S3", open: 7, closed: 4 },
  { w: "S4", open: 6, closed: 3 },
  { w: "S5", open: 5, closed: 4 },
  { w: "S6", open: 4, closed: 2 },
];

export const FS: FsNode[] = [
  { id: "root", name: "Kreluna", kind: "folder", parent: null },
  { id: "desk", name: "Desktop", kind: "folder", parent: "root" },
  { id: "docs", name: "Documenti", kind: "folder", parent: "root" },
  { id: "down", name: "Download", kind: "folder", parent: "root" },
  { id: "img", name: "Immagini", kind: "folder", parent: "root" },
  { id: "music", name: "Musica", kind: "folder", parent: "root" },
  { id: "video", name: "Video", kind: "folder", parent: "root" },
  { id: "share", name: "Condivisi", kind: "folder", parent: "root" },
  { id: "sys", name: "Sistema", kind: "folder", parent: "root" },
  { id: "legacy", name: "Legacy", kind: "folder", parent: "sys" },
  { id: "native", name: "Pacchetti", kind: "folder", parent: "sys" },
  { id: "lavoro", name: "Lavoro", kind: "folder", parent: "docs", orbit: "lavoro" },
  { id: "personale", name: "Personale", kind: "folder", parent: "docs", orbit: "personale" },
  { id: "studio", name: "Studio", kind: "folder", parent: "docs", orbit: "studio" },
  { id: "progetti", name: "Progetti", kind: "folder", parent: "docs", orbit: "progetti" },
  { id: "finanza", name: "Finanza", kind: "folder", parent: "docs", orbit: "finanza" },
  { id: "famiglia", name: "Famiglia", kind: "folder", parent: "personale", orbit: "personale" },
  { id: "foto", name: "Foto", kind: "folder", parent: "personale", orbit: "personale" },
  { id: "clienti", name: "Clienti", kind: "folder", parent: "lavoro", orbit: "lavoro" },
  { id: "fatture", name: "Fatture", kind: "folder", parent: "finanza", orbit: "finanza" },
  { id: "casa", name: "Casa", kind: "folder", parent: "personale", orbit: "personale" },
  { id: "idee", name: "Idee", kind: "folder", parent: "studio", orbit: "studio" },
  { id: "lw-clienti", name: "Clienti", kind: "folder", parent: "lavoro", orbit: "lavoro" },
  { id: "lw-docs", name: "Documenti", kind: "folder", parent: "lavoro", orbit: "lavoro" },
  { id: "lw-proj", name: "Progetti", kind: "folder", parent: "lavoro", orbit: "lavoro" },
  { id: "lw-fat", name: "Fatture", kind: "folder", parent: "lavoro", orbit: "finanza" },
  { id: "lw-prev", name: "Preventivi", kind: "folder", parent: "lavoro", orbit: "lavoro" },
  { id: "lw-meet", name: "Riunioni", kind: "folder", parent: "lavoro", orbit: "lavoro" },
  {
    id: "f-prev",
    name: "Preventivo Rossi.pdf",
    kind: "file",
    parent: "lw-prev",
    mime: "pdf",
    size: "240 KB",
    updated: "2 min fa",
    content: "Preventivo lavori — Cliente Rossi.\nImporto in revisione. Nessun invio automatico.",
  },
  {
    id: "f-pptx",
    name: "Presentazione Progetto.pptx",
    kind: "file",
    parent: "progetti",
    mime: "pptx",
    size: "4.1 MB",
    updated: "15 min fa",
    content: "Bozza presentazione progetto villa.",
  },
  {
    id: "f-doc",
    name: "Contratto Bianchi.docx",
    kind: "file",
    parent: "lw-docs",
    mime: "docx",
    size: "88 KB",
    updated: "3 ore fa",
    content: "Contratto Bianchi Srl — in attesa di firma umana.",
  },
  {
    id: "f-xls",
    name: "Report Finanziario.xlsx",
    kind: "file",
    parent: "fatture",
    mime: "xlsx",
    size: "1.2 MB",
    updated: "5 ore fa",
    content: "Report Q2. Cifre interne, non pubblicare.",
  },
  {
    id: "f-piano",
    name: "Piano progetto.docx",
    kind: "file",
    parent: "docs",
    mime: "docx",
    size: "112 KB",
    updated: "14/05/2024",
    content: "Piano di progetto Kreluna.",
  },
  {
    id: "f-budget",
    name: "Budget 2026.xlsx",
    kind: "file",
    parent: "docs",
    mime: "xlsx",
    size: "640 KB",
    updated: "13/05/2024",
    content: "Budget interno 2026.",
  },
  {
    id: "f-fat",
    name: "Fattura_0424.pdf",
    kind: "file",
    parent: "docs",
    mime: "pdf",
    size: "180 KB",
    updated: "12/05/2024",
    content: "Fattura 0424 — scadenza 18 agosto.",
  },
  {
    id: "f-pres",
    name: "Presentazione.pptx",
    kind: "file",
    parent: "docs",
    mime: "pptx",
    size: "2.8 MB",
    updated: "10/05/2024",
    content: "Presentazione commerciale.",
  },
  {
    id: "f-luna",
    name: "Core.luna",
    kind: "file",
    parent: "native",
    mime: "luna",
    size: "12 KB",
    updated: "Oggi",
    content: serializeLuna(PACKAGES[0]!),
  },
  {
    id: "f-luna-office",
    name: "Office.luna",
    kind: "file",
    parent: "native",
    mime: "luna",
    size: "11 KB",
    updated: "Oggi",
    content: serializeLuna(PACKAGES[1]!),
  },
  {
    id: "f-luna-cyber",
    name: "Cyber.luna",
    kind: "file",
    parent: "native",
    mime: "luna",
    size: "10 KB",
    updated: "Oggi",
    content: serializeLuna(PACKAGES[2]!),
  },
  {
    id: "f-luna-flow",
    name: "Fatture.luna",
    kind: "file",
    parent: "native",
    mime: "luna",
    size: "8 KB",
    updated: "Oggi",
    content: serializeLuna(PACKAGES[3]!),
  },
  {
    id: "f-luna-lib",
    name: "Note.luna",
    kind: "file",
    parent: "native",
    mime: "luna",
    size: "6 KB",
    updated: "Oggi",
    content: serializeLuna(PACKAGES[4]!),
  },
  {
    id: "f-luna-spec",
    name: "FORMATO.md",
    kind: "file",
    parent: "native",
    mime: "md",
    size: "4 KB",
    updated: "Oggi",
    content:
      "# LUNA/1\n\nUn file .luna è testo firmato, non un binario estraneo.\n\n1. Prima riga: `LUNA/1`\n2. Manifesto JSON: id, versione, runtime luna-1, permessi, humanGate\n3. Sigillo luna-fp1: impronta del manifesto\n\nNon è PE, ELF o Mach-O. Un .exe può stare sul disco, ma il runtime Luna non lo esegue.\nOgni azione rilevante resta `ask` o `deny`.",
  },
  {
    id: "f-exe",
    name: "legacy-setup.exe",
    kind: "file",
    parent: "legacy",
    mime: "exe",
    size: "18 MB",
    updated: "Oggi",
    meta: "4d 5a 90 00 03 00 00 00 04 00 00 00 ff ff 00 00",
    content:
      "Pacchetto .exe di un altro sistema. Kreluna lo conserva e lo legge, ma non lo esegue.",
  },
  {
    id: "desk1",
    name: "Leggimi.md",
    kind: "file",
    parent: "desk",
    mime: "md",
    size: "2 KB",
    updated: "Oggi",
    content:
      "# Kreluna\n\nQuesto è il filesystem nativo della sessione.\nImporta i tuoi file, anche .exe: restano nel disco Kreluna.\nI programmi nativi sono pacchetti .luna.",
  },
  {
    id: "pic1",
    name: "Mediterraneo.jpg",
    kind: "file",
    parent: "img",
    mime: "img",
    size: "340 KB",
    updated: "Oggi",
    content: "/os/wallpaper.jpg",
  },
  {
    id: "pic2",
    name: "Foto Cantiere.jpg",
    kind: "file",
    parent: "foto",
    mime: "img",
    size: "2.1 MB",
    updated: "1 ora fa",
    content: "/os/orbit-wall.jpg",
  },
  { id: "w-mare", name: "Mare.jpg", kind: "file", parent: "img", mime: "img", size: "280 KB", updated: "Oggi", content: "/os/walls/mare.jpg" },
  { id: "w-costa", name: "Costa.jpg", kind: "file", parent: "img", mime: "img", size: "440 KB", updated: "Oggi", content: "/os/walls/costa.jpg" },
  { id: "w-ghiaccio", name: "Ghiaccio.jpg", kind: "file", parent: "img", mime: "img", size: "410 KB", updated: "Oggi", content: "/os/walls/ghiaccio.jpg" },
  { id: "w-colline", name: "Colline.jpg", kind: "file", parent: "img", mime: "img", size: "460 KB", updated: "Oggi", content: "/os/walls/colline.jpg" },
  { id: "w-notte", name: "Notte.jpg", kind: "file", parent: "img", mime: "img", size: "300 KB", updated: "Oggi", content: "/os/walls/notte.jpg" },
  { id: "w-anelli", name: "Anelli.jpg", kind: "file", parent: "img", mime: "img", size: "330 KB", updated: "Oggi", content: "/os/walls/anelli.jpg" },
];

export const ACTIVITY: Activity[] = [
  { id: "ac1", title: "Preventivo Rossi.pdf", when: "2 min fa", mime: "pdf", fileId: "f-prev" },
  { id: "ac2", title: "Presentazione Progetto", when: "15 min fa", mime: "pptx", fileId: "f-pptx" },
  { id: "ac3", title: "Foto Cantiere", when: "1 ora fa", mime: "img", fileId: "pic2" },
  { id: "ac4", title: "Email Bianchi Srl", when: "2 ore fa", mime: "docx", fileId: "f-doc" },
  { id: "ac5", title: "Contratto Firma.docx", when: "3 ore fa", mime: "docx", fileId: "f-doc" },
];

export const REMINDERS: Reminder[] = [
  { id: "r1", title: "Riunione con Cliente Rossi", when: "Domani, 10:00" },
  { id: "r2", title: "Scadenza Fattura", when: "18 Agosto 2026" },
];
